Readiness config
hmcts/bulk-scan-processor pull request #1550
Opened 2020-09-24 12:56 UTC by apereverzin

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/BPS-1347

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-09-25 14:09 UTC, akomisarek approved these changes

2020-09-25 14:09 UTC, akomisarek commented on src/main/resources/application.yaml
> +          include: readinessState, db
Hi Andrey, is the readinessState required? What is it giving us?

2020-09-28 10:04 UTC, rkondratowicz requested changes
unanswered question

2020-09-29 09:27 UTC, apereverzin commented
Failing in CI

2020-09-29 09:27 UTC, closed without merging